{
  "formatVersion": "1.1",
  "component": {
    "group": "com.aoeiuv020",
    "module": "sdk-aarlibrary",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-aarlibrary-2.0.0.aar",
          "url": "sdk-aarlibrary-2.0.0.aar",
          "size": 2984,
          "sha512": "d097cf3af1dd590e5904249102c8628710c29e439cd6c5f777007a6eea1fb9907b1d49439d11cdbb49f319b20cc26d7722e2195a92a31bff95a71263f304e2e4",
          "sha256": "aae80cc6001dc5fe1e4b4b3f48808b32edc314070bfe520316f5285b595d9046",
          "sha1": "f6d85215dd003325d14da731143ceb0c0d89402c",
          "md5": "6654340da240f215a715501200106b21"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.aoeiuv020",
          "module": "sdk-jarlibrary",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-bom",
          "version": {
            "requires": "2.0.13"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-aarlibrary-2.0.0.aar",
          "url": "sdk-aarlibrary-2.0.0.aar",
          "size": 2984,
          "sha512": "d097cf3af1dd590e5904249102c8628710c29e439cd6c5f777007a6eea1fb9907b1d49439d11cdbb49f319b20cc26d7722e2195a92a31bff95a71263f304e2e4",
          "sha256": "aae80cc6001dc5fe1e4b4b3f48808b32edc314070bfe520316f5285b595d9046",
          "sha1": "f6d85215dd003325d14da731143ceb0c0d89402c",
          "md5": "6654340da240f215a715501200106b21"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-aarlibrary-2.0.0-sources.jar",
          "url": "sdk-aarlibrary-2.0.0-sources.jar",
          "size": 1429,
          "sha512": "2e5ed83944fd6466986ce24db114a4c36425965d192f88a36e7ad4fa1bc9a6a50aae0fd264f4f0c3d01d988d748e895749547f5b74197abd78dc067c23f9e702",
          "sha256": "c56e63c449dcb033f17a2458cc40a2398b4797b6e9528b88d700d654bf17e648",
          "sha1": "0967ea636dc2004399d04f2d42da8f4205b765dc",
          "md5": "3f44e1d78b885d7efff1a0f16d0e7209"
        }
      ]
    }
  ]
}
