{
  "formatVersion": "1.1",
  "component": {
    "group": "com.aoeiuv020",
    "module": "sdk-jarlibrary",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-jarlibrary-2.0.0.jar",
          "url": "sdk-jarlibrary-2.0.0.jar",
          "size": 4737,
          "sha512": "8cff548cf94be557c360b27725204166ae595d6465fcb19d22b69b57f4d4386f379b3c29695b2b1be6117b7b4c44f5593a53ea9119caa1daf31bef88714c1e8f",
          "sha256": "3704aafe89e7eec21afb7d4bfe1580e625ed5abcec1e4ef4c0b6682dbd03244f",
          "sha1": "187f1e38f4b7183083cef4d27cc1c55900eb1478",
          "md5": "4d6b95706822c8bf4edf43807c298f23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-bom",
          "version": {
            "requires": "2.0.13"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-jarlibrary-2.0.0.jar",
          "url": "sdk-jarlibrary-2.0.0.jar",
          "size": 4737,
          "sha512": "8cff548cf94be557c360b27725204166ae595d6465fcb19d22b69b57f4d4386f379b3c29695b2b1be6117b7b4c44f5593a53ea9119caa1daf31bef88714c1e8f",
          "sha256": "3704aafe89e7eec21afb7d4bfe1580e625ed5abcec1e4ef4c0b6682dbd03244f",
          "sha1": "187f1e38f4b7183083cef4d27cc1c55900eb1478",
          "md5": "4d6b95706822c8bf4edf43807c298f23"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-jarlibrary-2.0.0-sources.jar",
          "url": "sdk-jarlibrary-2.0.0-sources.jar",
          "size": 1304,
          "sha512": "ac03ef32671a7c5fd84e1ea9aeac02e2d7cce416d6c28c183dd25207d7dbdc3e8367c19eaee8e613786ca8c805a096c229a3d2b7ff7cd0a3664f18c3280bd4c7",
          "sha256": "7f0f2782d68896e0e1cc2fcc65285b00a0a4a60544e2e95dbd69301e96c26a89",
          "sha1": "f04f3556027983c3b4fb5ee9704cf63851ea91a5",
          "md5": "bbd1906434b43cd6d87d601f53a046ca"
        }
      ]
    }
  ]
}
